### ISSUE TITLE
My key no longer works?

### ISSUE THREAD

**Issue by Fee920** [cumincode/frameserver-issues#2]
FrameServer is no longer activited anymore and asking for key.  I enter my key but getting unable to activiate license message.

**Comment by malini-cumincode** [comment]
Looking at our logs, we notice that you've bought FrameServer version 4.1, but you have version 4.0 running. Is that correct? Can you download the latest version from our website and try that?

**Comment by Fee920** [comment]
it's working with v4.2, thanks.  Since I purchased 4.1, will the key work
for all new releases 4.1+?

**Comment by malini-cumincode** [comment]
Yes, it should work for all releases 4.1 and above until the next major release. In future, if we have a major release coming out we may have an upgrade offer for existing users.
